#!/usr/bin/bash


filename=${1:-Gutenberg/Wonder.txt}

ls -l ${filename}



cat ${filename}| tr '[:upper:]' '[:lower:]'| grep -oE "[a-z']{2,}" | grep -Fvwf Gutenberg/stopwords  | sort | uniq -c  | sort -nr | head -n 15